string command       # "take_photo" or other future commands
int32 identifier     # YOLO class ID (64 for mouse, etc.)
---
geometry_msgs/Point[] coordinates  # Array of detected object positions
bool success         # Whether detection was successful
string message       # Status message